trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  phpRepository: 'drupal-wxt/php'
  webRepository: 'drupal-wxt/web'
  containerRegistry: "Drupal-WxT-BNET (MGMT-Docker)"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    pool: PrDc-PBMM_Dev-AgentPool-VM

    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the php image
      inputs:
        repository: '${{ variables.phpRepository }}'
        containerRegistry: '${{ variables.containerRegistry }}'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: |
          $(tag)
          latest
        arguments: '--target php'
    - task: Docker@2
      displayName: Push the php image
      inputs:
        containerRegistry: '${{ variables.containerRegistry }}'
        repository: '${{ variables.phpRepository }}'
        command: 'push'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build the web image
      inputs:
        repository: '${{ variables.webRepository }}'
        containerRegistry: '${{ variables.containerRegistry }}'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: |
          $(tag)
          latest
        arguments: '--target web'
    - task: Docker@2
      displayName: Push the web image
      inputs:
        containerRegistry: '${{ variables.containerRegistry }}'
        repository: '${{ variables.webRepository }}'
        command: 'push'
        tags: |
          $(tag)
          latest
- stage: Deploy_to_Dev
  displayName: Deploy to Dev
  jobs:
  - job: Deploy_Web_Image
    pool: PrDc-PBMM_Dev-AgentPool-VM
    steps:
    - task: AzureRmWebAppDeployment@4
      env: 
        NODE_OPTIONS: '--use-openssl-ca'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Drupal-WxT-BNET (Dev)'
        appType: 'webAppContainer'
        WebAppName: 'wxt-web'
        deployToSlotOrASE: true
        ResourceGroupName: 'PrDc-PBMM-ILBASE3-ase'
        SlotName: 'production'
        DockerNamespace: '${{ variables.webRepository }}'
        DockerRepository: '${{ variables.containerRegistry }}'
        DockerImageTag: '$(tag)'
  - job: Deploy_PHP_Image
    pool: PrDc-PBMM_Dev-AgentPool-VM
    steps:
    - task: AzureRmWebAppDeployment@4
      env: 
        NODE_OPTIONS: '--use-openssl-ca'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Drupal-WxT-BNET (Dev)'
        appType: 'webAppContainer'
        WebAppName: 'wxt-php'
        deployToSlotOrASE: true
        ResourceGroupName: 'PrDc-PBMM-ILBASE3-ase'
        SlotName: 'production'
        DockerNamespace: '${{ variables.phpRepository }}'
        DockerRepository: '${{ variables.containerRegistry }}'
        DockerImageTag: '$(tag)'